In [1]:
import numpy as np

In [2]:
# rzutowanie z listy

In [3]:
moja_lista = [1,2,3]

In [4]:
arr = np.array(moja_lista) # rzutowanie listy na obiekt numpy

In [9]:
arr

array([1, 2, 3])

In [18]:
moja_macierz = [[1,2,3],[4,5,6],[7,8,9]] # lista list na macierz

In [19]:
np.array(moja_macierz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# generownaie macierzy:

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(0,10,2) # start, stop, krok

array([0, 2, 4, 6, 8])

In [31]:
# generowanie samymi zerami

In [32]:
np.zeros((4,5)) # 4 wiersze i 5 kolumn

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
# generowanie samymi jedynkami

In [34]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
# funkcja linspace: Zwraca równomiernie rozmieszczone liczby w określonym przedziale

In [37]:
# od n do m z krokiem k
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [38]:
# tworzenie macierzy kwadratowej z jedynkami na przekątnej - macierz jednostkowa NxN

In [39]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
# random number

In [43]:
np.random.rand(5) # Rozkład jednostajny ciągły od 0 do 1

array([0.33353953, 0.20825595, 0.15824284, 0.48105669, 0.91000034])

In [44]:
np.random.rand(5,5)

array([[0.83958259, 0.9437077 , 0.26361767, 0.36897468, 0.82086698],
       [0.84851335, 0.76715488, 0.17112013, 0.75638755, 0.5283933 ],
       [0.9037117 , 0.63868447, 0.89612055, 0.80660953, 0.69468824],
       [0.38464672, 0.39228307, 0.09696136, 0.0892034 , 0.35934965],
       [0.27013053, 0.97546017, 0.83090257, 0.2407332 , 0.04751463]])

In [47]:
np.random.randn(2,4) # Rozkład normalny

array([[-0.26350872, -0.90517612,  0.11517953, -2.08179786],
       [ 0.22037262, -1.48265027,  0.2312151 ,  1.10820345]])

In [51]:
np.random.randint(1,100) # losowo wybrana liczba z przedziału od <n do N)

18

In [54]:
np.random.randint(1,100,10) # od (włącznie), do (bez włączności), ile liczb ma zwrócić

array([42, 72,  3, 50, 23, 50, 22, 24, 63,  8])

In [ ]:
np.random.uniform

In [55]:
# zmaiana wymiarów

In [56]:
arr = np.arange(25)

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
ranarr = np.random.randint(0,50,10)

In [59]:
ranarr

array([ 4,  8, 49, 44, 24, 43, 46, 29, 27, 13])

In [61]:
arr.reshape(5,5) # wymair NxM musi zgadazać się z rozmiarem tablicy przez zmianą

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# maksymalna i minilana wartość w macierzy

In [65]:
ranarr.max() # zwraca max wartość

49

In [66]:
ranarr.min() # zwraca min wartość

4

In [67]:
ranarr

array([ 4,  8, 49, 44, 24, 43, 46, 29, 27, 13])

In [69]:
ranarr.argmax() # zrwaca indeks na którym znajduje się wartość max

2

In [74]:
ranarr.argmin() # zrwaca indeks na którym znajduje się wartość min

0

In [75]:
# rozmiar

In [76]:
arr.shape

(25,)

In [77]:
arr.reshape(5,5).shape

(5, 5)

In [78]:
# typ danych w macierzy

In [2]:
arr.dtype

NameError: name 'arr' is not defined

In [8]:
lista_liczb = []
print(lista_liczb)
lista_liczb = [i for i in range(4)]
print(lista_liczb)

[]
[0, 1, 2, 3]


In [4]:
for i in range(4):
    lista_liczb.append(i)

In [5]:
lista_liczb

[0, 1, 2, 3]

In [9]:
A = np.array([1,2,3])

In [10]:
A.shape

(3,)

In [11]:
B = np.array([[1, 2], [3, 4]])

In [12]:
B.shape

(2, 2)