In [34]:
import numpy as np

In [ ]:
# wstęp

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[-1:]

array([10])

In [11]:
arr[-2:]

array([ 9, 10])

In [12]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
# zastąpinie kilku elementów jedną wartością:
arr[0:5] = 99

In [14]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [16]:
arr = np.arange(0,11)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# uwaga dotycząca przypisywania!!
wycinek = arr[0:6]

In [19]:
wycinek

array([0, 1, 2, 3, 4, 5])

In [20]:
wycinek[:] = 99

In [21]:
wycinek

array([99, 99, 99, 99, 99, 99])

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
# dane nie są kopiowane, tylko działa na orginalnej tablicy
# ziwazane jest to z optymalizacją pamięci dla dużych macierzy

In [27]:
# aby temu zapobiec należy "ręcznie kopiować tablice":

In [28]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
kopia = arr.copy()

In [26]:
kopia

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
# po zmianie kopii, orinał zostanie

In [30]:
kopia[:] = 100

In [32]:
kopia

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [33]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [35]:
# indeksowanie

In [41]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [43]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [44]:
# dwa formaty:

In [45]:
# pierwszy

In [46]:
arr_2d[0][0] # element z n wiersza i m kolumny

5

In [47]:
arr_2d[0]

array([ 5, 10, 15])

In [57]:
arr_2d[2][1]

40

In [58]:
# drugi

In [59]:
arr_2d[0,0]

5

In [60]:
arr_2d[:,2]

array([15, 30, 45])

In [61]:
arr_2d[1,:]

array([20, 25, 30])

In [62]:
# wycinek kawałka maicerzy

In [63]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [65]:
arr_2d[:2,1:] # weź wiersze <0,2) oraz kolumny od 1 do końca

array([[10, 15],
       [25, 30]])

In [68]:
arr_2d[:2,1]

array([10, 25])

In [71]:
arr_2d[1:,1]

array([25, 40])

In [72]:
# dobór pod pewnymi warunkami

In [74]:
arr = np.arange(1,11)

In [77]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [79]:
warunek = arr > 5

In [80]:
warunek

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [82]:
arr[warunek] # zwróci tylko te elementy, które są prawdziwe

array([ 6,  7,  8,  9, 10])

In [83]:
arr[arr>5] # sposób bez dodatkowej zmiennej

array([ 6,  7,  8,  9, 10])

In [84]:
arr[arr<3]

array([1, 2])

In [85]:
# wspólne zadanie:
# matrix slicing

In [86]:
arr = np.arange(50).reshape(5,10)

In [87]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [89]:
# przykład: wyciągnąć 13,14 i 23,24:

In [90]:
arr[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [3]:
import numpy as np
A = np.array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [4]:
A

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [5]:
A[0]

array([12, 13, 14, 15])

In [7]:
A[0][-1]

15